#!/bin/bash

echo "🧪 Testing Passman TUI Clipboard Functionality"
echo "=============================================="

echo "📋 Test Steps:"
echo "1. Run: ./target/release/keytui-tui"
echo "2. Navigate to an entry (use ↑/↓ if needed)"
echo "3. Press Enter to copy password"
echo "4. App should auto-quit"
echo "5. Test clipboard: xclip -selection clipboard -o"
echo "6. You should see the password in clipboard"
echo ""
echo "🔧 Manual Test:"
echo "1. Launch TUI: ./target/release/keytui-tui"
echo "2. Select entry: Use ↑/↓ to navigate"
echo "3. Copy password: Press Enter"
echo "4. Check clipboard: xclip -selection clipboard -o"
echo ""
echo "✅ Expected Result:"
echo "- Password should be copied to clipboard"
echo "- App should auto-quit after copying"
echo "- Clipboard should contain the password"
echo ""
echo "🚨 If clipboard doesn't work:"
echo "- Install xclip: sudo apt install xclip"
echo "- Or install wl-copy: sudo apt install wl-clipboard"
